# Generated by Django 4.0.3 on 2022-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
