# Generated by Django 4.0.3 on 2022-03-20 23:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VfxCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidVfxProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, help_text='You can set up price up to $999.99.This is the max price.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('watermarkproduct', models.FileField(blank=True, help_text='Provide a WatermarkProduct.This product is just a showcase to Customers. Only .mp4 is accepted', null=True, upload_to='VFX/free/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('watermarkfreeproduct', models.FileField(blank=True, help_text='Provide a Watermark free Product to distribute to Customers .Only .mp4 is accepted', null=True, upload_to='VFX/paid/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mvfx.vfxcategory', verbose_name='Vfx Category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
                ('setdiscount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ehub.setdiscount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaidVfxProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.purchasedproduct')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mvfx.paidvfxproduct')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FreeVfxProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('watermarkfreeproduct', models.FileField(blank=True, help_text='Provide a Product without any Watermark included in it. Only .mp4 is accepted', null=True, upload_to='VFX/free/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mvfx.vfxcategory', verbose_name='Product Category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
            ],
        ),
    ]
