# Generated by Django 4.0.3 on 2022-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mvfx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freevfxproduct',
            name='watermarkfreeproduct',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paidvfxproduct',
            name='watermarkfreeproduct',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='paidvfxproduct',
            name='watermarkproduct',
            field=models.URLField(null=True),
        ),
    ]
