# Generated by Django 4.0.3 on 2022-03-20 23:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidWebTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, help_text='You can set up price up to $999.99.This is the max price.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('999.99'))])),
                ('demoproduct', models.FileField(blank=True, help_text='An show-case/Demo video for you web template. Only .mp4 is accepted', null=True, upload_to='WebTemplates/free/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('url', models.URLField(blank=True, help_text='an link of the website if it exists.', null=True)),
                ('file', models.FileField(help_text='Provide a file that contains the source code of the web template .Only .zip and .rar are accepted', null=True, upload_to='Web templates/free/%y', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mweb.templatecategory', verbose_name='Template Category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
                ('setdiscount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ehub.setdiscount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaidWebTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_by', models.CharField(max_length=20, null=True)),
                ('addtoDpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.purchasedproduct')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mweb.paidwebtemplate')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FreeWebTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('demoproduct', models.FileField(blank=True, help_text='An show-case/Demo video for you web template. Only .mp4 is accepted', null=True, upload_to='WebTemplates/free/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('url', models.URLField(blank=True, help_text='an link of the website if it exists.', null=True)),
                ('file', models.FileField(help_text='Provide a file that contains the source code of the web template .Only .zip and .rar are accepted', null=True, upload_to='Web templates/free/%y', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mweb.templatecategory', verbose_name='Product Category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ehub.profile')),
            ],
        ),
    ]
